# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Cameron's Blog
description: >- # this means to ignore newlines until "baseurl:"
  (SuYeon)
baseurl: "" # the subpath of the site
url: "https://gottgam.github.io" # the base hostname & protocol for the site
og_image: # /assets/img/profile-pic.png
# google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Work
    - name: Blog

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: me@suyeonpark.info
      link: mailto:me@suyeonpark.info
    # - name: WeChat
      # value: YourWeChatUsername
      # link: "#"
  follow:
    - name: Twitter
      link: http://twitter.com/rollingbb8
      username: "@rollingbb8"
    # - name: Facebook
      # link: http://facebook.com/YourFacebookUsername
    - name: LinkedIn
      link: http://linkedin.com/in/suyeonparkbb8
    - name: GitHub
      link: http://github.com/gottgam
    - name: Dribbble
      link: https://dribbble.com/rollingbb8
    # - name: RSS
      # link: /feed.xml

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
