# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Boiiing
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of the site
url: "https://suyonpark.github.io" # the base hostname & protocol for the site
og_image: favicon.ico
# google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Categories

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: me@suyonpark.com
      link: mailto:me@suyonpark.com
    # - name: WeChat
      # value: YourWeChatUsername
      # link: "#"
  follow:
    - name: Twitter
      link: http://twitter.com/rollingbb8
      username: "@rollingbb8"
    # - name: Facebook
      # link: http://facebook.com/YourFacebookUsername
    - name: LinkedIn
      link: http://linkedin.com/in/suyonpark
    - name: GitHub
      link: http://github.com/suyonpark
    - name: Behance
      link: https://www.behance.net/suyonpark
    # - name: RSS
      # link: /feed.xml

# Build settings
markdown: kramdown
highlighter: rouge
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1

theme: jekyll-theme-minimal